### ISSUE TITLE
Warning in the HA log

### ISSUE THREAD

**Issue by pepe59** [TheRealWaldo/AMG8833-ESPHOME#4]
I'm testing the component and everything is working fine so far.
After restarting HA, I have a warning in the log. Is it possible to remove it somehow?

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 17:17:06 (1 occurrences)
Last logged: 17:17:06

Entity camera.prototype_thermal_camera (<class 'custom_components.thermal_vision.camera.ThermalVisionCamera'>) implements device_state_attributes. Please report it to the custom component author.
```

**Comment by TheRealWaldo** [comment]
Thanks for the report!  Would you mind posting this on the Integration issues as the issue would be there?

**Comment by pepe59** [comment]
If I understand correctly, I should post a warning here https://github.com/TheRealWaldo/thermal
Yes, I will add it there.
